### ISSUE TITLE
problem with timeouts in version 4.0.0

### ISSUE THREAD

**Issue by derekclee** [jaimeiniesta/metainspector#112]
In version 3, timeouts seem fine. In version 4.0.0, when I try

```
page = MetaInspector.new('http://www.wrota.podkarpackie.pl/pl/um', :connection_timeout => 5, :read_timeout => 5)
```
It takes much longer than 5 seconds to timeout.  I ran across that site which doesn't respond (hope it stays that way until you check it out...) . 

Thanks.

**Comment by jaimeiniesta** [comment]
Hey @derekclee thanks for your report, and happy new year!

Keep in mind that by default, we'll retry up to 3 times, so if you set a timeout of 5, it will be retried 3 times, for a total of 20 seconds until the timeout is reached.

You can set the number or retries like this:

```ruby
page = MetaInspector.new('http://www.wrota.podkarpackie.pl/pl/um', :connection_timeout => 5, :read_timeout => 5, :retries => 0)
```

I'd use at least 1 retry, however. Maybe just set a shorter timeout?

**Comment by derekclee** [comment]
@jaimeiniesta Thanks for clarifying how timeouts work.  Sorry it took me so long to reply. It seems to be working fine. Happy belated new year!

**Comment by jaimeiniesta** [comment]
You're welcome!
