### ISSUE TITLE
Best guess at title?

### ISSUE THREAD

**Issue by mmmmmrob** [jaimeiniesta/metainspector#117]
Many pages I come across have poorly formed html in a variety of ways — I'm sure you've seen it too.

At the moment #title returns the inner_text of the 'head title' in the html. Limitations of this are that sometimes it returns an array, rather than a simple string and, of course, there isn't always a title element in the head.

I propose #best_title to do some smart guessing in a similar way to #images.best.

Initially to pick the longest title from a set of candidates: 'head title', 'og:title', 'body title', 'h1'.first

Does that sound useful?

rob

**Comment by jaimeiniesta** [comment]
:+1:

I think we should have a look at the [pismo](https://github.com/peterc/pismo) gem and learn some tricks from it.

My main worries about that are losing accuracy, I mean, we should differentiate somehow between exact matches and guessed matches, which is exactly what you propose by having two separate methods.

But maybe we should separate this (as a major version) in two different parsers, one for the exact matches and one for the guesses.

I don't know yet, maybe it would make sense instead to have `page.titles` (plural) to return all the titles found, and `page.titles.best` return the longest one?

**Comment by mmmmmrob** [comment]
That might be a nice way to go — I've just sent a PR with what I initially suggested.

**Comment by jaimeiniesta** [comment]
I like what you propose on the PR by now, we can add it on 4.2.1 and think about all the other changes later.

Let me know when you're ready with the PR.

**Comment by jaimeiniesta** [comment]
PR merged, closing this issue.
