### ISSUE TITLE
how the page.links.internal works, a wired thing met

### ISSUE THREAD

**Issue by metrue** [jaimeiniesta/metainspector#122]
@jaimeiniesta 

when I inspect some page with domain like "xxx.com", I got "xxx.net/abc" in page.links.internal.
xxx.net/abc is not internal relationship of "xxx.com", right?

**Comment by jaimeiniesta** [comment]
Right, that's not the way it's supposed to work. Can you give me a concrete example of a real URL so I can reproduce the bug?

**Comment by metrue** [comment]
@jaimeiniesta 

sure, I met this issue when I use it in my web crawler.
I will send you the example when met it again.

**Comment by jaimeiniesta** [comment]
Alright, feel free to reopen this issue when you can provide a sample URL. :+1:
