### ISSUE TITLE
Cleaning/Deduping URIs

### ISSUE THREAD

**Issue by mmmmmrob** [jaimeiniesta/metainspector#131]
We're working on code to spot canonical URLs for pages and use them. In cases where a canonical URL isn't provided, we're also interested removing tracking elements to give us the best chance of having URLs for the same page be the same in our data.

I'm thinking about something like:

"Page.untracked_url returns the url of the page with known tracking elements, such as ?utm=, removed"

Is anyone else doing/done this?

Is metainspector a happy place for this functionality to live?

**Comment by jaimeiniesta** [comment]
Yes, definitely support to get both the canonical and the untracked url of a page would be a good Metainspector feature.

**Comment by jschwindt** [comment]
I've done that outside Metainspector but it would be a good idea to incorporate that feature. If nobody is working on it I can send a PR. @mmmmmrob/@jaimeiniesta: let me know if you want me to start working on it.

**Comment by jaimeiniesta** [comment]
Now that we can get the canonical links and tracking parameters, is there anything more to be added regarding this issue or should we close it by now?

**Comment by jaimeiniesta** [comment]
@mmmmmrob ping :)

**Comment by jaimeiniesta** [comment]
@mmmmmrob I'm closing this, please reopen if there's anything else you want to add.
