### ISSUE TITLE
Absolutify and unrelativize head links

### ISSUE THREAD

**Issue by jaimeiniesta** [jaimeiniesta/metainspector#136]
As commented on https://github.com/jaimeiniesta/metainspector/pull/132#issuecomment-103422390

**Comment by jschwindt** [comment]
@jaimeiniesta/@mmmmmrob: I have some time these days, do you want me to work on this? I'd need 4.5 to be released ;-)

**Comment by jaimeiniesta** [comment]
OK for me, unless @mmmmmrob prefers to do that himself.

Anyway @jschwindt you don't need to wait for the release, you can install the gem directly from github, the features are already merged in master:

http://bundler.io/git.html

**Comment by jschwindt** [comment]
I've just added another commit to my PR that solves this ticket!

**Comment by jaimeiniesta** [comment]
Closed via https://github.com/jaimeiniesta/metainspector/commit/e0b3808a3de1516bef04a22499652a2ab480911c
