### ISSUE TITLE
get size of best image

### ISSUE THREAD

**Issue by nivla** [jaimeiniesta/metainspector#141]
Hi,
I want to get the width and height of the best image, there is a way to get it?

thanks beforehand.

**Comment by jaimeiniesta** [comment]
You need to use both `page.images.best` to get the URL of the best image, and then look for its dimensions on `page.images.with_size`.

But, currently `page.images.with_size` does not include `page.images.best` in the case the best image comes from an owner suggestion. So you might not find it there.

I'll open a separate issue to improve this.

Thanks!

**Comment by jaimeiniesta** [comment]
This is the best solution that we have now, you can use the [FastImage](https://github.com/sdsykes/fastimage) gem to get the size of the best image. As this image can come from a meta tag, there's no width/height resolution on the HTML so you need to use this library.

```ruby
page = MetaInspector.new('http://jaimeiniesta.com')
width, height = FastImage.size(page.images.best)
```

**Comment by jaimeiniesta** [comment]
Also, there's no need to separately install FastImage, it's already a dependency of MetaInspector.

**Comment by nivla** [comment]
Thanks. That solution works great :dancer:
