### ISSUE TITLE
warn_level: :store and links.external bug (invalid byte sequence in UTF-8)

### ISSUE THREAD

**Issue by dentarg** [jaimeiniesta/metainspector#150]
```ruby
[7] pry(main)> MetaInspector.new("https://lanoralemos.wordpress.com", warn_level: :store).ok?
=> true
[8] pry(main)> MetaInspector.new("https://lanoralemos.wordpress.com", warn_level: :store).links.external
ArgumentError: invalid byte sequence in UTF-8
from /Users/dentarg/.gem/ruby/2.2.3/gems/metainspector-4.7.2/lib/meta_inspector/parsers/links.rb:22:in `block in http'
```

but

```ruby
MetaInspector.new("https://lanoralemos.wordpress.com", warn_level: :store).links
```

works without exceptions though. I saved the output from `.links` in pry [in a gist](https://gist.githubusercontent.com/dentarg/dc50d64bdaa35dd112cf/raw/6a265577526285dbbe09c860d4d953ceedba517a/metainspector_issue.txt), maybe it could be useful (I haven't looked more closely on what's causing this).

Should  `warn_level: :store` be able to store this? Maybe putting `ArgumentError` on that list isn't what we want to do...

**Comment by jaimeiniesta** [comment]
This is failing because one of the links in this page has an invalid byte sequence:

`http://element�wgarderoby.com/`

Now, yes, this should be properly handled by the ExceptionLog. Will fix it.

**Comment by dentarg** [comment]
:sparkling_heart:

**Comment by jaimeiniesta** [comment]
Can you try this with 5.0.0 and see how it goes? It should raise a `MetaInspector::ParserError`.

**Comment by jaimeiniesta** [comment]
It keeps failing on 5.0.1, needs some love:

https://metainspectordemo.herokuapp.com/scrape?url=https%3A%2F%2Flanoralemos.wordpress.com

**Comment by dentarg** [comment]
@jaimeiniesta I'm sorry, but we ended up taking the `rescue` route with MetaInspector for now (see code snippet below), so until that changes, I'm afraid I will be less active on the issues here.

```ruby
  def fetch_links_from_page(url)
    options = {
      warn_level: :store,
      download_images: false,
      html_content_only: true,
      headers: {
        "User-Agent" => USER_AGENT
      },
    }

    result = MetaInspector.new(url, options)

    return [] unless result.ok?

    result.links.external
  rescue => e
    @logger.info("Error: #{e.message}")
    []
  end
```
