### ISSUE TITLE
Amazon scraping error?

### ISSUE THREAD

**Issue by andiruleu** [jaimeiniesta/metainspector#159]
I'm testing out the demo, and its returning internal server error. Does it not scrape Amazon links?

**Comment by jaimeiniesta** [comment]
It should scrape them. Please give me a sample URL to test.

**Comment by andiruleu** [comment]
Its interesting... I was getting internal server error, and now its scraping it, but its scraping captcha letters: https://metainspectordemo.herokuapp.com/scrape?url=http%3A%2F%2Fwww.amazon.com%2Fgp%2Fproduct%2FB00VFVUAMQ I've tested with other amazon products too, all the same.

**Comment by jaimeiniesta** [comment]
That's interesting!

I can scrape it correctly from my development computer:

```ruby
➔ irb
2.2.3 :001 > require 'metainspector'
 => true
2.2.3 :002 > MetaInspector.new('http://www.amazon.com/gp/product/B00VFVUAMQ').title
 => "Amazon.com : SJCAM Original SJ4000 WiFi Version Full HD 1080P 12MP Diving Bicycle Action Camera 30m Waterproof Car DVR Sports DV with Waterproof Case (Black)+Extra 2 Batteries : Camera & Photo"
```

I guess that what's happening is that Amazon is doing some checks, probably based on the IP address. As the demo is on a Heroku server, Amazon might think that it's an automated script (and that's exactly what it is!), and returning a "Robot check" page in front.

So, in short, MetaInspector works, but what it's receiving from Amazon is a "Robot check" page with a captcha.

**Comment by andiruleu** [comment]
That is pretty interesting... you may be right! I am testing on a localhost:3000 also...!

**Comment by m-walker** [comment]
There's no need for me to go into the details since most of been stated already, but I'm getting the same error in production (i.e. "robot check") when dealing with Amazon links. My app is hosted on Heroku as well.

Has anybody found a successful workaround for this?

By the way, thanks so much for your work on this gem!
