### ISSUE TITLE
Scraping Amazon Image Data, there's 1 image with long image src

### ISSUE THREAD

**Issue by andiruleu** [jaimeiniesta/metainspector#161]
Hello!
I have an app where I can display amazon images, but there's always an image where the src is super long, per the attached image.

I was wondering if there's a way to remove this specific image? I want it removed because users are allowed to choose the images they want to save, and if the user chooses an image with this src, it doesn't have the proper image url where we can display it in our app.

![screen shot 2015-12-03 at 9 22 12 pm](https://cloud.githubusercontent.com/assets/1781551/11582459/f417cb80-9a03-11e5-8e2d-90694c168bdf.png)

**Comment by gabceb** [comment]
Hi!

The src of the image you are looking at is the actual image content base64 enconded. This technique is used to avoid downloading files for things you would like to display w/o making another request to get the content.

You should be able to detect (and remove) this image by using a simple regex that will looks for 'data:image' on the images array. Im also pretty sure your app framework/programming language should be able to handle base64 representation of images but you'll prob have to special case these.

Hope this answers your question and clarifies some things.

**Comment by andiruleu** [comment]
hmmm, I'm no expert at this, but do you think you can start me off with this? Where would I put the simple regex?

I have this in my controller:

    def gear_link_meta
      meta_tags = MetaInspector.new(params[:link])
      @images = meta_tags.try(:images) if meta_tags.present?
    end 

Thanks!

**Comment by jaimeiniesta** [comment]
Closing this as it's not a MetaInspector issue.
