### ISSUE TITLE
Scrape content from links?

### ISSUE THREAD

**Issue by oyeanuj** [jaimeiniesta/metainspector#163]
Thank you @jaimeiniesta for the library! Wondering if metainspector has options to or if it possible to include some options to scrape text content of off a webpage as well and make it accessible as a text field in the hash. 

I am aware that at that point, it becomes more than meta, and more of an extract api but helps towards the same goal. 

Comparison of a random url using metainspector and Embedly Extract: 

[URL] (http://www.thequint.com/opinion/2015/12/16/three-laws-for-a-more-liberal-india)

[MetaInspector](https://metainspectordemo.herokuapp.com/scrape?url=http%3A%2F%2Fwww.thequint.com%2Fopinion%2F2015%2F12%2F16%2Fthree-laws-for-a-more-liberal-india)

[Embedly Extract](http://embed.ly/docs/explore/extract?url=http%3A%2F%2Fwww.thequint.com%2Fopinion%2F2015%2F12%2F16%2Fthree-laws-for-a-more-liberal-india)

**Comment by jaimeiniesta** [comment]
This is not currently possible but it would be certainly an interesting feature to have.
