### ISSUE TITLE
Can't read some Arabic articles

### ISSUE THREAD

**Issue by abdelhady** [jaimeiniesta/metainspector#167]
Metainspector can't read title/description of [this article](http://klmty.net/476092-%D8%A8%D8%A7%D9%84%D9%81%D9%8A%D8%AF%D9%8A%D9%88____%D9%85%D8%B5%D8%B7%D9%81%D9%89_%D8%A8%D9%83%D8%B1%D9%8A____%D8%A7%D9%86%D8%AA%D8%AE%D8%A7%D8%A8%D8%A7%D8%AA_%D8%A7%D9%84%D8%A7%D8%A6%D8%AA%D9%84%D8%A7%D9%81_%D8%BA%D9%8A%D8%B1_%D9%86%D8%B2%D9%8A%D9%87%D8%A9_%D9%88%D9%85%D9%88%D8%AC%D9%87%D8%A9_%D9%84%D9%81%D9%88%D8%B2_%D8%A3%D8%B4%D8%AE%D8%A7%D8%B5_%D8%A8%D8%B9%D9%8A%D9%86%D9%87%D8%A7.html) properly, it reads a decoded state of its arabic content!

**Comment by jaimeiniesta** [comment]
Thanks for the report, that's [verified](https://metainspectordemo.herokuapp.com/scrape?url=http%3A%2F%2Fklmty.net%2F476092-%25D8%25A8%25D8%25A7%25D9%2584%25D9%2581%25D9%258A%25D8%25AF%25D9%258A%25D9%2588____%25D9%2585%25D8%25B5%25D8%25B7%25D9%2581%25D9%2589_%25D8%25A8%25D9%2583%25D8%25B1%25D9%258A____%25D8%25A7%25D9%2586%25D8%25AA%25D8%25AE%25D8%25A7%25D8%25A8%25D8%25A7%25D8%25AA_%25D8%25A7%25D9%2584%25D8%25A7%25D8%25A6%25D8%25AA%25D9%2584%25D8%25A7%25D9%2581_%25D8%25BA%25D9%258A%25D8%25B1_%25D9%2586%25D8%25B2%25D9%258A%25D9%2587%25D8%25A9_%25D9%2588%25D9%2585%25D9%2588%25D8%25AC%25D9%2587%25D8%25A9_%25D9%2584%25D9%2581%25D9%2588%25D8%25B2_%25D8%25A3%25D8%25B4%25D8%25AE%25D8%25A7%25D8%25B5_%25D8%25A8%25D8%25B9%25D9%258A%25D9%2586%25D9%2587%25D8%25A7.html)

PRs welcome!
