### ISSUE TITLE
Dependency issue with addressable gem

### ISSUE THREAD

**Issue by ronniekessler** [jaimeiniesta/metainspector#176]
Tried to add metainspector v 5.0 and got the following Bundler issue.

Bundler could not find compatible versions for gem "addressable":
  In Gemfile:
    capybara (~> 2.6) was resolved to 2.6.2, which depends on
      addressable

    capybara (~> 2.6) was resolved to 2.6.2, which depends on
      addressable

**    metainspector (>= 5.0.1, ~> 5.0) was resolved to 5.0.1, which depends on
      fastimage (~> 1.8) was resolved to 1.9.0, which depends on
        addressable (~> 2.3.5)**

**    metainspector (>= 5.0.1, ~> 5.0) was resolved to 5.0.1, which depends on
      addressable (~> 2.4)**

**Comment by jaimeiniesta** [comment]
Thanks @ronniekessler -- the blocker here was fastimage 1.9.0, that sets a dependency on addressable ~> 2.3.5 but we need ~> 2.4

I've updated the dependency on fastimage to ~>1.8.1 which will set us behind 1.9.0, in this version they allow addressable 2.4.

This has been released on metainspector 5.0.2 - please try it out!

I'll leave this issue open as a reminder to help the fastimage team to update the addressable dependency to 2.4 and beyond.

**Comment by ronniekessler** [comment]
Sure, I will test this over the next few days.

On 24 February 2016 at 20:18, Jaime Iniesta <notifications@github.com>
wrote:

> Thanks @ronniekessler <https://github.com/ronniekessler> -- the blocker
> here was fastimage 1.9.0, that sets a dependency on addressable ~> 2.3.5
> but we need ~> 2.4
>
> I've updated the dependency on fastimage to ~>1.8.1 which will set us
> behind 1.9.0, in this version they allow addressable 2.4.
>
> This has been released on metainspector 5.0.2 - please try it out!
>
> I'll leave this issue open as a reminder to help the fastimage team to
> update the addressable dependency to 2.4 and beyond.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaimeiniesta/metainspector/issues/176#issuecomment-188154971>
> .
>



-- 
Ronnie Kessler
rlkessler@gmail.com | +61 403 066607 | au.linkedin.com/in/ronniekessler

**Comment by jaimeiniesta** [comment]
We upgraded to the latest fastimage and addressable versions in https://github.com/jaimeiniesta/metainspector/commit/4f5590081c6afc88639de1a389d02d1d9c806336 but forgot to close this issue. Done!
