### ISSUE TITLE
Outdated documentation regarding timeouts

### ISSUE THREAD

**Issue by fschwahn** [jaimeiniesta/metainspector#182]
I think the documentation regarding timeouts/retries (https://github.com/jaimeiniesta/metainspector#timeout--retries) is outdated. It talks about catching `Faraday::TimeoutError`, however in the code this exception is catched and wrapped with a `MetaInspector::TimeoutError`. So the example should reflect this change - I briefly looked at the history, and looks like this part of the README predates the latest changes to the exception system.

**Comment by jaimeiniesta** [comment]
Thanks @fschwahn, you're right, we recently changed this part and forgot to update the README about that. Will do.

**Comment by jaimeiniesta** [comment]
Fixed, thanks @fschwahn :)

**Comment by fschwahn** [comment]
Thanks for fixing it! :)
