### ISSUE TITLE
How does the MetaInspector Demo (https://metainspectordemo.herokuapp.com) scrape Amazon.com URL?

### ISSUE THREAD

**Issue by AbraarAriquePro** [jaimeiniesta/metainspector#184]
I have used MetaInspector for scraping Amazon.com product pages in order to gather some basic data such as product title, price, and image. It works fine on my local machine, however, when I deploy the app to Heroku Amazon gives me a "Robot Check" page instead of the actual product page.

When I tried the same URL in your MetaInspector Demo https://metainspectordemo.herokuapp.com it was able to successfully scrape all the data from the Amazon page. How does that work?

Can you please show me the source code of the MetaInspector Demo app?

**Comment by jaimeiniesta** [comment]
Sure, here's the code:

https://github.com/jaimeiniesta/metainspectordemo
