### ISSUE TITLE
RequestError on existing url

### ISSUE THREAD

**Issue by tchret** [jaimeiniesta/metainspector#189]
``` 
MetaInspector.new('http://www.davinciapps.com')
# MetaInspector::RequestError: SSL_connect returned=1 errno=0 state=error: certificate verify failed
```

@jaimeiniesta: otherwise, ❤️ this gem

**Comment by tchret** [comment]
also:
```
MetaInspector.new('https://www.helpscout.net/embed-tools/')
# ArgumentError: invalid byte sequence in UTF-8
```

**Comment by jaimeiniesta** [comment]
Thanks for the feedback! Verified in Ruby 2.0.0 and MetaInspector 5.2.3.

**Comment by jaimeiniesta** [comment]
For the SSL part, as we use Faraday to make the request, you could do this to disable SSL certification:

https://github.com/jaimeiniesta/metainspector#disabling-ssl-verification-or-any-other-faraday-options

But use this with care, this has [security implications](https://github.com/lostisland/faraday/wiki/Setting-up-SSL-certificates#solutions-to-avoid)

**Comment by jaimeiniesta** [comment]
For the UTF-8 part, we _might_ use this:

http://api.rubyonrails.org/classes/ActiveSupport/Multibyte/Chars.html#method-i-tidy_bytes

**Comment by jaimeiniesta** [comment]
Related: https://github.com/jaimeiniesta/metainspector/issues/129

**Comment by jaimeiniesta** [comment]
@tchret for the second example, on 'https://www.helpscout.net/embed-tools/', the problem was that the response was gzipped. Since MetaInspector 5.3.1 we now automatically deflate this, so this has been fixed. Related: #191

**Comment by jaimeiniesta** [comment]
@tchret as for the SSL part you can disable SSL verification, I'm going to close this issue. Feel free to reopen if needed, and thanks!
