### ISSUE TITLE
Unreadable text for some pdf urls

### ISSUE THREAD

**Issue by prabond** [jaimeiniesta/metainspector#196]
For most pdf files I tested the gem returns empty description. However, for some it is returning unreadable text like "ÿ!m`”  Afvye6j 8}FMUÜq@ûÉJ °MsaR9SÜhs&DG?B£Jc gõh¨FÕ)ÿÄ ë4«'[rÄÖ[ÙÚúdÝÒHvÔ ‘åÙó*WV^»cÜ5IªWzÅ}hÏö·’¬^VS0q´@QÔpÆæÂ’©#IC^L"õK8aµXÉïÄ2zU…"

Following are couple of urls it fails for:
http://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf
http://stluciadance.com/prospectus_file/sample.pdf

**Comment by jaimeiniesta** [comment]
MetaInspector is an HTML scraper, it can't process PDFs.
