### ISSUE TITLE
Wrong scrapped info (title/description/image), even with the demo

### ISSUE THREAD

**Issue by abdelhady** [jaimeiniesta/metainspector#198]
I'm trying to scrape [this url](https://inbound.org/blog/what-1200-of-the-worlds-best-marketers-think-about-the-future-of-social-media) from inbound.org, 

when using the version 5.0.1 (in my code), it gave me empty title/description (with wrong image),
& when using [the demo](https://metainspectordemo.herokuapp.com/), it gave me [wrong data](https://metainspectordemo.herokuapp.com/scrape?url=https%3A%2F%2Finbound.org%2Fblog%2Fwhat-1200-of-the-worlds-best-marketers-think-about-the-future-of-social-media) (title/description/image),

I doubted that the url's meta-tags are wrong (for example it has an empty description), but when I tried Facebook's debugger, it gave the [right results](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Finbound.org%2Fblog%2Fwhat-1200-of-the-worlds-best-marketers-think-about-the-future-of-social-media).

Good Luck.

**Comment by jschwindt** [comment]
@abdelhady: The <title> tag of that page is initially empty and it is filled up later using javascript. Also, all the social meta tags al empty and the first <h1> has only "Log In". I don't think there is much that can be done using MetaInspector :(

**Comment by abdelhady** [comment]
Well, you are right, I just thought that since Facebook is successfully scrapping it, then there might be a way of doing so! .. but I can't think of a solution for it.

Anyway, thanks for your response, & good luck.

**Comment by jaimeiniesta** [comment]
There might be a way of doing this using something like PhantomJS, but this falls out of the scope of MetaInspector right now... Anyway I'm open for PRs if anyone can think of a way to do this.

Thanks!
