### ISSUE TITLE
Redirection to URL with anchor cause 404

### ISSUE THREAD

**Issue by artem-russkikh** [jaimeiniesta/metainspector#201]
FaradayMiddleware::FollowRedirects has bug that cause redirection to wrong url (url with wrong encoded anchor)

https://github.com/lostisland/faraday_middleware/issues/138

Issue can be reproduced on demo using this link:
```
https://bit.ly/2jDtwKC
```

Also on dev machine using metainspector 4.7.2

Seems that issue is already fixed (month ago)

**Comment by jaimeiniesta** [comment]
Thanks, I verified the bug on the demo:

https://metainspectordemo.herokuapp.com/scrape?url=https%3A%2F%2Fbit.ly%2F2jDtwKC

It looks like the fix will be updating the dependencies, feel free to send a PR if you wish!

**Comment by artem-russkikh** [comment]
ok! i'll do it soon

**Comment by jaimeiniesta** [comment]
Thanks! The dependencies update is on its way.
