### ISSUE TITLE
Encoding::CompatibilityError: incompatible character encodings: UTF-7 and UTF-8

### ISSUE THREAD

**Issue by roback** [jaimeiniesta/metainspector#204]
Im getting the following error in MetaInspector 5.2.2. I have only ever noticed this for the URL http://www.imusausa.com/. I suspect that UTF-7 isn't that common since I didn't know it existed before seeing this error.

To reproduce the error: `MetaInspector.new("http://www.imusausa.com/")`

```
Encoding::CompatibilityError: incompatible character encodings: UTF-7 and UTF-8
  meta_inspector/request.rb:31:in `tr'
    response.body.tr("\000", '') if response
  meta_inspector/request.rb:31:in `read'
    response.body.tr("\000", '') if response
  meta_inspector/document.rb:104:in `document'
    @request.read
  meta_inspector/document.rb:78:in `to_s'
    document
  meta_inspector/parser.rb:33:in `parsed'
    @parsed ||= Nokogiri::HTML(@document.to_s)
```

I also get the same error in 5.4.0:

```ruby
[1] pry(main)> MetaInspector::VERSION
=> "5.4.0"
[2] pry(main)> MetaInspector.new("http://www.imusausa.com/")
Encoding::CompatibilityError: incompatible character encodings: UTF-7 and UTF-8
from ~/.gem/ruby/2.2.4/gems/metainspector-5.4.0/lib/meta_inspector/request.rb:32:in `tr'
```

**Comment by jaimeiniesta** [comment]
UTF-7! First time I hear about it as well. No idea, will have a look when I can, PRs welcome :)

**Comment by jnarowski** [comment]
Added an option here to force specific encodings:
https://github.com/jaimeiniesta/metainspector/pull/231

**Comment by jaimeiniesta** [comment]
I've tried this example on MetaInspector 5.6.0 and it no longer fails. Feel free to reopen if it can be reproduced again.
