### ISSUE TITLE
Comparison with Metascraper/Scrappy

### ISSUE THREAD

**Issue by oyeanuj** [jaimeiniesta/metainspector#205]
Hi @jaimeiniesta, a more general question - 

I came across these two libraries that seem to have a higher hit rate and wondering your thoughts on those features and if you could see them being incorporated in `metainspector`.

1. [Metascraper](https://github.com/ianstormtaylor/metascraper): This library uses a lot of css classname fallbacks and seems to gets a [much higher hit rate](https://github.com/ianstormtaylor/metascraper#comparison), especially with author and publisher information.

2. [Scrappy](https://github.com/blakeembrey/node-scrappy): This library works on pdfs, videos, docs, etc to essentially extract similar information that `metainspector` is trying for.

Not sure if these features are beyond the scope of the library, but wanted to atleast put it for discussion.

Thanks!

**Comment by jaimeiniesta** [comment]
Hi @oyeanuj !

As long as the features are focused on HTML pages (no PDFs or other format), I'll gladly accept pull requests for them!

About the comparison, it's interesting to look at them but also notice that for Metascraper they're comparing with node-metainspector - which is a project based on metainspector, but a different one.
