### ISSUE TITLE
How can I get h1 tag?

### ISSUE THREAD

**Issue by tackeyy** [jaimeiniesta/metainspector#208]
Thank you for creating this gem!

I`d like to get h1 tag like page.title.
Is there any way or options?

**Comment by jaimeiniesta** [comment]
Thank you!

If you use `page.best_title`, the first `h1` tag will be used as the last candidate:

https://github.com/jaimeiniesta/metainspector/blob/master/lib/meta_inspector/parsers/texts.rb#L36-L41

Other than that, there's no way to specifically get an `h1` tag.

**Comment by tackeyy** [comment]
I got it. Thank you!
