### ISSUE TITLE
undefined method internal for #<Array:0x007f85868dbe78>

### ISSUE THREAD

**Issue by vanegomez** [jaimeiniesta/metainspector#210]
Hello,

Thank you for writing this gem.

I'm not sure why Im getting this error using the link_checker.rb example for a rails app. I'm getting all the links but all and internal method are not working.
```
 page.links.all.internal.each do |link|
      @queue.push(link) if should_be_enqueued?(link)
 end
```
Thank you.

**Comment by jaimeiniesta** [comment]
Hey @vanegomez you're using it wrong, if you want to get the internal links it's just `page.links.internal`.

Take a look at the README:

https://github.com/jaimeiniesta/metainspector#links

Feel free to reopen this issue if you think there's still an issue!

**Comment by vanegomez** [comment]
@jaimeiniesta sorry I think I didn't explain myself better. I was trying to use your example with rails https://github.com/jaimeiniesta/metainspector/blob/master/examples/link_checker.rb  
I get the following errors: 
```
`process_next_on_queue': undefined method `all' for #<Array:0x007fcad988c6a0> (NoMethodError)
```

for this method: 

```
page.links.all.select {|l| l =~ /^http(s)?:\/\//i}.each do |link|
        check_status(link, page.url)
end
```
if I remove the `all` from select it keeps going, but then I get another error. I'm able to get all the links but no able to use the 'external' or 'internal' method for the array of links. 
```
`process_next_on_queue': undefined method `internal' for #<Array:0x007ff83e9445b0> (NoMethodError)
```
Here is the file, which is the same thing as your example.

```
# A basic spider that will follow internal links, checking broken links
#
# Usage example:
#
#   ruby link_checker.rb example.com


# puts "Using MetaInspector #{MetaInspector::VERSION}"
require 'open-uri'
require 'metainspector'

  class LinkChecker
    def initialize(url)
      @url      = url
      @queue    = []
      @visited  = []
      @ok       = []
      @broken   = {}

      check
    end

    def report
      puts "\n#{@broken.size} broken links found."

      @broken.each do |link, from|
        puts "\n#{link} linked from"
        from.each do |origin|
          puts " - #{origin}"
        end
      end
    end

    private

    def check
      # Resolves redirections of initial URL before placing it on the queue
      @queue.push(MetaInspector.new(@url).url)

      process_next_on_queue while @queue.any?
    end

    def process_next_on_queue
      page = MetaInspector.new(@queue.pop)

      page.links.select {|l| l =~ /^http(s)?:\/\//i}.each do |link|
        check_status(link, page.url)
      end

      @visited.push(page.url)

      page.links.internal.each do |link|
        @queue.push(link) if should_be_enqueued?(link)
      end

      show_stats
    end

    # Checks the response status of the linked_url and stores it on the ok or broken collections
    def check_status(linked_url, from_url)
      if @broken.keys.include?(linked_url)
        # This was already known to be broken, we add another origin
        @broken[linked_url] << from_url
      else
        if !@ok.include?(linked_url)
          # We still don't know about this link status, so we check it now
          if reachable?(linked_url)
            @ok << linked_url
          else
            @broken[linked_url] = [from_url]
          end
        end
      end
    end

    def should_be_enqueued?(url)
      !(@visited.include?(url) || @broken.include?(url) || @queue.include?(url))
    end

    def show_stats
      puts "#{'%3s' % @visited.size} pages visited, #{'%3s' % @queue.size} pages on queue, #{'%2s' % @broken.size} broken links"
    end

    # A page is reachable if its response status is less than 400
    # In the case of exceptions, like timeouts or server connection errors,
    # we consider it unreachable
    def reachable?(url)
      page = MetaInspector.new(url)

      if page.response.status < 400
        true
      else
        false
      end
    rescue
      false
    end
  end

# Get the starting URL
url = ARGV[0] || (puts "Enter a starting url"; gets.strip)
LinkChecker.new(url).report
```

**Comment by jaimeiniesta** [comment]
Hey @vanegomez let's try to get this working!

You shouldn't loop directly `page.links`. Instead you have to choose if you want all the links (`page.links.all`) or the internal links (`page.links.internal`), for example. See the README for more options.

For example, this will print all the links:

```ruby
page.links.all.each do |link|
  puts link
end
```

And this will only print the internal links:

```ruby
page.links.internal.each do |link|
  puts link
end
```

Makes sense?

If you want, upload your script to a gist or git repo and I can send you a pull request to make it work.

**Comment by jaimeiniesta** [comment]
Alright, I catched an error here:

https://gist.github.com/vanegomez/de917d1d5c7e1bdfae2d17db982b774f#file-external_link_checker-rb-L46

`page.links.select {|l| l =~ /^http(s)?:\/\//i}.each do |link|` 

should be, I guess,

`page.links.external.select {|l| l =~ /^http(s)?:\/\//i}.each do |link|`

Not sure what you want to achieve (the example script is a bit old), but the thing here is that you cannot call `.select` directy on `page.links` as this is not a collection, it's a scraper class. You need to do `page.links.all.select` or `page.links.internal.select`, `page.links.external.select`, etc.

Also, check the class name here https://gist.github.com/vanegomez/de917d1d5c7e1bdfae2d17db982b774f#file-external_link_checker-rb-L104

**Comment by jaimeiniesta** [comment]
I simplified the example script, the idea there was to check the status only of the HTTP links, `select`ing only those that started with "http(s)". But there's a simpler way for that, just using `links.http`:

https://github.com/jaimeiniesta/metainspector/commit/ba6bfdcb022860e7b98d8524d90981a39ceaee9a

Take a look the Links section in the README:

https://github.com/jaimeiniesta/metainspector#links

**Comment by vanegomez** [comment]
'page.links' this comes as collection in pry 

![screen shot 2017-05-30 at 10 26 29 am](https://cloud.githubusercontent.com/assets/10290117/26593757/8bc31a00-4522-11e7-9aa3-4513ba256baf.png)
![screen shot 2017-05-30 at 10 27 31 am](https://cloud.githubusercontent.com/assets/10290117/26593819/b30a19a6-4522-11e7-9208-28d68b03dddf.png)

**Comment by jaimeiniesta** [comment]
What MetaInspector version are you using?

**Comment by vanegomez** [comment]
just added `gem 'metainspector'` to my gemfile 

omg thank you so much for helping out

**Comment by jaimeiniesta** [comment]
It looks like you might be using an old version of MetaInspector. Back in the days, `page.links` was a collection, but now it doesn't work that way. Please update to the latest version `5.4.1` :)

**Comment by jaimeiniesta** [comment]
If for some reason you can't upgrade to the latest version, here's the documentation for release 3.3.0 where `page.links` was still a collection

https://github.com/jaimeiniesta/metainspector/tree/fc96ae8bf421fabb15889bee3cbfee18af0fefcd

But, the 3.3.0 release is 3 years old, this is super old and unsupported. You're encouraged to upgrade to 5.4.1 and get all the fixes and improvements since then :)

**Comment by vanegomez** [comment]
thank you @jaimeiniesta I had to specify the gem version in my gemfile in order to work.

**Comment by jaimeiniesta** [comment]
Cool, glad you fixed it. :)
