### ISSUE TITLE
Using of `Nokogiri::XML` instead of `Nokogiri::HTML`

### ISSUE THREAD

**Issue by alfie-max** [jaimeiniesta/metainspector#212]
I was using this gem for getting the external links on a page, but when it encountered html pages with issues, the rest of the page is ignored and that caused many of the links not to be fetched. 

So was playing around with nokogiri and tried using `Nokogiri::XML` and that gave me all the links. irrespective of the html errors.

Not sure what the difference is in the implementation. But would be good if someone can look into it.

Maybe XML parsing ignores all html errors??

**Comment by jaimeiniesta** [comment]
@alfie-max sorry for taking so long to reply. Can you please provide and example URL that we can try? What errors are you getting?

**Comment by jaimeiniesta** [comment]
@alfie-max I'll close this, feel free to reopen if you can provide an example URL to reproduce this.
