### ISSUE TITLE
Add best_author method

### ISSUE THREAD

**Issue by oyeanuj** [jaimeiniesta/metainspector#213]
Hi @jaimeiniesta! Thanks for the library! Wondering if you'd consider adding `best_author` method similar to `best_title`, and `best_description` methods that you have today?

**Comment by jaimeiniesta** [comment]
Sure, good idea!

I'll welcome a PR for that.

**Comment by lesleyhogg** [comment]
Hello. Here's some code I wrote to add `best_author`. Would this work? If so, I can go ahead and create tests for it and then make a PR.

for texts.rb:
`# Returns the document author
def best_author
  @best_author ||= find_best_author
end

# An author getter that returns the first non-nil description
# from the following candidates:
# - the standard meta description
# - a link with the relational attribute "author"
# - address tag which may contain the author
# - the twitter:creator meta tag for the username
def find_best_author
  candidates = [
    meta['author'],
    parsed.css('a[rel="author"]').first,
    parsed.css('address').first,
    meta['twitter:creator']
  ]
  candidates.find { |x| !x.to_s.empty? }
end`

**Comment by jaimeiniesta** [comment]
Hello @lesleyhogg , yes, it sounds good, please go ahead!

**Comment by jaimeiniesta** [comment]
Closing this as @lesleyhogg PR has been merged. Thanks!
