### ISSUE TITLE
What's this doing on my logs?

### ISSUE THREAD

**Issue by uhlhosting** [jaimeiniesta/metainspector#218]
```
unix: - - [18/Oct/2017:23:32:16 +0200] "GET / HTTP/1.0" 503 1545 "-" "MetaInspector/5.4.1 (+https://github.com/jaimeiniesta/metainspector)"
unix: - - [18/Oct/2017:23:41:51 +0200] "GET / HTTP/1.0" 503 1545 "-" "MetaInspector/5.4.1 (+https://github.com/jaimeiniesta/metainspector)"
```

**Comment by jaimeiniesta** [comment]
Hello, MetaInspector is a ruby gem used to read web pages and extract information from them, like the title, description, links, etc.

MetaInspector is polite and identifies itself via the User-Agent string:

https://github.com/jaimeiniesta/metainspector#headers

In short, someone used MetaInspector to read your web pages.
