### ISSUE TITLE
ArgumentError: invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by georgecheng** [jaimeiniesta/metainspector#220]
**Ruby**: 2.4.1
**Rails**: 5.1.4
**MetaInspector**: 5.4.1
**Problem URL**: `http://www.stephguerin.com/archives/dashthis-est-maintenant-rendu-a-275-employes/`

---

Hi, I tried looking for solutions everywhere before posting this issue, but have been unable to resolve it. I'm getting an `ArgumentError: invalid byte sequence in UTF-8` error on this URL: `http://www.stephguerin.com/archives/dashthis-est-maintenant-rendu-a-275-employes/`

The code that creates the error: 
`page = MetaInspector.new("http://www.stephguerin.com/archives/dashthis-est-maintenant-rendu-a-275-employes/")`

I'm not sure, but it might be related to #189. Any ideas?

**Comment by gchiaren** [comment]
+1 here. 

**Ruby:** 2.4.1
**Rails:** 5.1.5
**MetaInspector:** 5.4.1
**Problem URL:** `https://forum.bodybuilding.com/showthread.php?t=168913393`

**Comment by luctus** [comment]
Same here...

Ruby: 2.4.1
Rails: 5.1.5
MetaInspector: 5.4.1
Problem URL: http://www.plataformaurbana.cl/archive/2009/01/25/%C2%A1%C2%A1quiero-reciclar-%C2%BFdonde-reciclar/

**Comment by jaimeiniesta** [comment]
Thanks for the report! I'm very busy lately to investigate this but I'll be happy to review PRs 👍

**Comment by jnarowski** [comment]
I'd be happy to issue a pull request for this. Can you add me as a contributor?

**Comment by gabceb** [comment]
Hi @jnarowski. You dont need to be added as a contributor to issue a PR. You do need to be a contributor to merge but others can do that for you. Cheers!

**Comment by jnarowski** [comment]
Added an option here to force specific encodings:
https://github.com/jaimeiniesta/metainspector/pull/231

**Comment by jaimeiniesta** [comment]
Fixed in https://github.com/jaimeiniesta/metainspector/commit/3e83bb84e981f2c46037bc6990ee51cbd0f5b352
