### ISSUE TITLE
Get all iframes in a page?

### ISSUE THREAD

**Issue by bragboy** [jaimeiniesta/metainspector#222]
How about something like this?

page.iframes.src - Gives me sources of the iframes present in the page

If you can implement this great. If not, I can submit a Pull request. Please let me know.

**Comment by jaimeiniesta** [comment]
Sounds like a good idea. It would be nice to get all the attributes of the iframes, not only the src, if possible. Please submit a PR.

**Comment by jaimeiniesta** [comment]
Closing this suggestion - PRs welcome!
