### ISSUE TITLE
RequestError: end of file reached

### ISSUE THREAD

**Issue by andresinaka** [jaimeiniesta/metainspector#226]
When doing the following I randomly get the `RequestError: end of file reached`

```
MetaInspector.new(
    url, 
    allow_non_html_content: true,
    connection_timeout: 10,
    read_timeout: 10,
    retries:1
)
```
Same link one time works the second time it doesn't. No clue what's going on!

**Comment by jaimeiniesta** [comment]
Can you provide an URL that we can try?

**Comment by jaimeiniesta** [comment]
@andresinaka we need an URL to be able to reproduce this, please provide an example so we can investigate.
