### ISSUE TITLE
data sources or external links

### ISSUE THREAD

**Issue by Mifrill** [jaimeiniesta/metainspector#229]
I want to say thanks for the excellent work, gem is very good.

How about data sources or external links, for example, from where the frames and js-libs used?

For example, if the site has a video, or the site displays products from another resource. It would be convenient to also display this information in your reports. Especially this applies to frames. Thank you

**Comment by jaimeiniesta** [comment]
Thanks for your kind words.

I'm open for reviewing a PR that adds the URLs of external sources, scripts, stylesheets, frames... Feel free to send it :+1:
