### ISSUE TITLE
A url containing utf-8 characters is manipulated, which leads to a page redirect

### ISSUE THREAD

**Issue by abdelhady** [jaimeiniesta/metainspector#232]
[This url](https://www.chaino.com/pulse/%D8%A7%EF%BB%B5%D9%8A%D8%A9-%D8%AF%D9%8A%D9%87-%D8%A8%D8%AA%D9%84%D8%AE%D8%A8%D8%B7%D9%86%D9%8A-%D8%B4%D9%88%D9%8A%D8%A9-%D9%81-%D9%84-%D9%85-%D8%A7-%D8%A3-%D9%86) has utf-8 characters (Arabic) in it, which seems to be manipulated just before scrapping, which leads to an undesired redirect to the site's error page,

I'm using version 5.0.1, but even the latest version has the issue, and [here is the wrong result](https://metainspectordemo.herokuapp.com/scrape?url=https%3A%2F%2Fwww.chaino.com%2Fpulse%2F%25D8%25A7%25EF%25BB%25B5%25D9%258A%25D8%25A9-%25D8%25AF%25D9%258A%25D9%2587-%25D8%25A8%25D8%25AA%25D9%2584%25D8%25AE%25D8%25A8%25D8%25B7%25D9%2586%25D9%258A-%25D8%25B4%25D9%2588%25D9%258A%25D8%25A9-%25D9%2581-%25D9%2584-%25D9%2585-%25D8%25A7-%25D8%25A3-%25D9%2586) (tested using the metainspector's own demo)

**Comment by jaimeiniesta** [comment]
Thanks for the bug report! I'll be happy to review a PR if you want to submit it.

**Comment by jaimeiniesta** [comment]
I verified that this fails with MetaInspector 5.6.0.

The URL linked above gets converted to this one when I copy it from Chrome:

```
https://www.chaino.com/pulse/%D8%A7%EF%BB%B5%D9%8A%D8%A9-%D8%AF%D9%8A%D9%87-%D8%A8%D8%AA%D9%84%D8%AE%D8%A8%D8%B7%D9%86%D9%8A-%D8%B4%D9%88%D9%8A%D8%A9-%D9%81-%D9%84-%D9%85-%D8%A7-%D8%A3-%D9%86
```

But as @abdelhady points out, the URL is wrongly manipulated somewhere and we get redirected to another one.

**Comment by jschwindt** [comment]
This is another URL normalization problem. I tried this:
```ruby
url = 'https://www.chaino.com/pulse/%D8%A7%EF%BB%B5%D9%8A%D8%A9-%D8%AF%D9%8A%D9%87-%D8%A8%D8%AA%D9%84%D8%AE%D8%A8%D8%B7%D9%86%D9%8A-%D8%B4%D9%88%D9%8A%D8%A9-%D9%81-%D9%84-%D9%85-%D8%A7-%D8%A3-%D9%86'

page = MetaInspector.new(url)
page.url
=> "https://www.chaino.com/error/pulsedeleted"

page = MetaInspector.new(url, normalize_url: false)
page.url == url
=> true

page.title
=> "\n" +
"    Abdelhady Muhammad: اﻵية ديه بتلخبطني شوية (فَلَمَّا أَنْ أَرَادَ أَنْ يَبْطِشَ بِالَّذِي هُوَ عَدُوٌّ لَهُمَا قَالَ يَا مُوسَى أَتُرِيدُ أَنْ تَقْتُلَنِي كَمَا قَتَلْتَ نَفْسًا بِالأَمْسِ)\n" +
"\n" +
"مش المفروض ان موسى قتله بالفعل \"الذي هو عدو لهما\" قبلها!! .. ياترى ترتيب القصة هنا كان ايه بالظبط؟ - Chaino"
```
So, with the option `normalize_url: false` works fine.

**Comment by abdelhady** [comment]
Sorry for the late response, I've just tried the `normalize_url: false` with upgrading to the latest version `5.6.0` & it worked fine with me, 
I guess I'm gonna close this issue then, thanks a lot for your follow up 🙂
