### ISSUE TITLE
Some page headers missing

### ISSUE THREAD

**Issue by danielbonnell** [jaimeiniesta/metainspector#234]
Hi,

I'm trying to check for the presence of the `content-security-policy` (CSP) header on a page (e.g. [this page has a CSP header](https://dc.curbed.com/2018/6/1/17418388/truss-virtual-reality-tours-northern-virginia-dc?utm_medium=FirmPlay&utm_source=LinkedIn&utm_campaign=ChiamakaE-8319&utm_term=dc.curbed.com&utm_content=4348)). When I check `page.response.headers` though, there is no CSP header, even though the Chrome inspector clearly shows that the header is there. Here is what MetaInspector shows. Am I missing something?

```
[14] pry(main)> page.response.headers
=> {"server"=>"nginx",
 "content-type"=>"text/html; charset=utf-8",
 "x-frame-options"=>"SAMEORIGIN",
 "x-xss-protection"=>"1; mode=block",
 "x-content-type-options"=>"nosniff",
 "cache-control"=>"max-age=0, must-revalidate",
 "x-request-id"=>"ec791bc81b2c29cf44265d37b81b475e45b53363",
 "x-runtime"=>"0.239128",
 "via"=>"1.1 varnish-v4, 1.1 varnish",
 "content-length"=>"134705",
 "accept-ranges"=>"bytes",
 "date"=>"Fri, 08 Jun 2018 21:11:34 GMT",
 "age"=>"0",
 "connection"=>"close",
 "set-cookie"=>"_chorus_geoip_continent=NA; expires=Sat, 09 Jun 2018 21:11:34 GMT; path=/;",
 "x-served-by"=>"cache-mdw17332-MDW",
 "x-cache"=>"MISS",
 "x-cache-hits"=>"0",
 "x-timer"=>"S1528492294.786769,VS0,VE329",
 "vary"=>
  "Accept-Encoding, Accept-Encoding, X-Chorus-Unison-Testing, X-Chorus-Require-Privacy-Consent, Origin, X-Forwarded-Proto, X-Chorus-Unison-Testing, X-Chorus-Require-Privacy-Consent"}

```
Thanks!

**Comment by jaimeiniesta** [comment]
Hey Daniel, thanks for the report!

I can verify that using MetaInspector 5.5.0 I don't see any CSP header on the server response. But I don't see it either using Chrome, can you show me how to find that? Maybe an screenshot would help.

On a first thought, this sounds like the server is giving different responses based on the User-Agent string or IP.

**Comment by danielbonnell** [comment]
I had the same thought about user agent. I tried overriding the default UA that MetaInspector sends with the same exact UA from my Chrome browser but I got the same headers. FWIW I noticed that the `content-length` in bytes differs substantially between Chrome (39948 bytes) and MetaInspector (134705 bytes), which would suggest to me that the web server somehow knows (even with the spoofed UA) that it's being scraped.

Here's a screenshot of that CSP header in Chrome.
<img width="1062" alt="screen shot 2018-06-11 at 9 13 00 am" src="https://user-images.githubusercontent.com/8513877/41237040-2f7b24ae-6d58-11e8-86e1-371c7f5de6d2.png">

**Comment by jaimeiniesta** [comment]
This could be because of an IP check. Are you getting the same results when you use MetaInspector in your dev machine, and when you do that from your servers? It's very typical that some servers ban traffic from Heroku or AWS for example.

**Comment by jaimeiniesta** [comment]
If you get the page using `curl -I url` from your console, do you get the `content-security-policy` response headers? I don't get them:

```
curl -I https://dc.curbed.com/2018/6/1/17418388/truss-virtual-reality-tours-northern-virginia-dc?utm_medium=FirmPlay&utm_source=LinkedIn&utm_campaign=ChiamakaE-8319&utm_term=dc.curbed.com&utm_content=4348

➔ HTTP/2 200
server: nginx
content-type: text/html; charset=utf-8
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
cache-control: max-age=0, must-revalidate
x-request-id: 17e678222cede5268176c4dff902207abbe51460
x-runtime: 0.238325
via: 1.1 varnish-v4
accept-ranges: bytes
date: Tue, 12 Jun 2018 08:58:50 GMT
via: 1.1 varnish
age: 132
set-cookie: _chorus_geoip_continent=EU; expires=Wed, 13 Jun 2018 08:58:50 GMT; path=/;
x-served-by: cache-lcy19229-LCY
x-cache: HIT
x-cache-hits: 1
x-timer: S1528793931.688110,VS0,VE2
vary: Accept-Encoding, Accept-Encoding, X-Chorus-Unison-Testing, X-Chorus-Require-Privacy-Consent, Origin, X-Forwarded-Proto, X-Chorus-Unison-Testing, X-Chorus-Require-Privacy-Consent
content-length: 117526
```

I think that the server is somehow guessing that the request comes from a browser, for instance via cookies, and given a different response in that case. Using `curl` you can make a raw request, more similar to the one that MetaInspector does. You can also try making the request with [Postman](https://www.getpostman.com/) if you prefer.

**Comment by danielbonnell** [comment]
This is interesting. I tried `curl`, same results you posted. I then went back, cleared my cache/cookies for that website, and now I'm not seeing the CSP header even in Chrome. Tried multiple reloads and still no CSP header. Definitely something interesting going on with that server.

**Comment by jaimeiniesta** [comment]
OK, then that definitely explains the issue, the server responds with the CSP depending on the cookies.

**Comment by jaimeiniesta** [comment]
Closing this issue, feel free to open a new one or a PR if you think there's anything we can improve in the code @danielbonnell :)
