### ISSUE TITLE
Customize scrape for selected page

### ISSUE THREAD

**Issue by arjunmenon** [jaimeiniesta/metainspector#236]
Hey
Sometimes Matainspector does not catch all relevant information from a site. Perhaps because it is structured in a non-standard way.

However, is it possible to specify the nodes to look for when it finishes to parse? I know I can further use `page.parsed` to get extra information, but I would like to return the results in the Metainspector hash itself?

A rules config would be nice.

How can we do it?

**Comment by jaimeiniesta** [comment]
Hello!

The standard way that is expected is that of an HTML page, of course :)

I think I don't really understand your rules config proposal, but I'm open for any suggestion you may have in the form of a pull request!

**Comment by jaimeiniesta** [comment]
Closing this, feel free to send a PR :)
