### ISSUE TITLE
Fix error in Ruby 3.1.1

### ISSUE THREAD

**Issue by jaimeiniesta** [jaimeiniesta/metainspector#287]
We've enabled CircleCI and discovered that we have some issues with Ruby 3.1.1:

https://app.circleci.com/pipelines/github/metainspector/metainspector/9/workflows/77b5e373-710d-401a-af2c-f6dabc0a6823/jobs/19

@jschwindt rings any bell?

**Comment by jaimeiniesta** [comment]
@jjb maybe you can take a look at this? This is failing in Ruby 3.1.1 (but works in other Ruby versions):

https://github.com/metainspector/metainspector/blob/master/spec/request_spec.rb#L80-L86

I'm asking because you were involved in this part of the code... back in 2014 ! :)

https://github.com/metainspector/metainspector/commit/a5627c4750af30dd4c8169cb03b961e10d3d253a

**Comment by jschwindt** [comment]
@jaimeiniesta unfortunately it doesn't ring any bell to me :(

**Comment by jaimeiniesta** [comment]
Hey @jschwindt no problem - we'll cut a release with Ruby 3.0 support and work on upgrading Faraday and the rest of the dependencies, we'll make it work with Ruby 3.1 eventually 👍

**Comment by jaimeiniesta** [comment]
Closed as we currently support Ruby from 2.6 to 3.2.
