### ISSUE TITLE
Error 404 when scrapping page accessible through browser.

### ISSUE THREAD

**Issue by ugran** [jaimeiniesta/metainspector#64]
Hi,

There is a new kind of problem I've got into.
Several days ago I could scrappe pages from zara's website, but now when I try, it gives me an open uri error 404. There is a problem when I try to pin the url on pinterest also, but facebook does it with ease.

For example:
http://www.zara.com/us/en/woman/coats/loose-fit-trench-coat-c367501p1933522.html

**Comment by TGots7** [comment]
HI, I am having the same problem, I am opening a html site scrapig getting the data properly then an error is firing after i get the data saying 404 error, do you knwo why this could be? thank you
