### ISSUE TITLE
smarter image picking

### ISSUE THREAD

**Issue by jjb** [jaimeiniesta/metainspector#90]
i'd like to be able to do smarter image picking somehow. we could…

* use og metadata for width and height to present to the user the og images in decreasing size (few sites will have both multiple images and the size data available though)
* download all images, determine their size, then present them in an array of decreasing size
* use nokogiri to somehow intelligently guess which images are from the content area of the page (there must be existing recipes for this out there)

thoughts?

this is maybe a 3.1 feature.

**Comment by mmmmmrob** [comment]
I've dropped in a PR for giving back a smarter largest image where OG and Twitter are missing.

**Comment by jaimeiniesta** [comment]
Does the new `page.images.largest` released in 4.2.0 solve this issue? Or would you still be wanting to add more features, like returning all the images ordered by size?

**Comment by jjb** [comment]
Hi -- the new feature looks awesome, thanks @mmmmmrob and @jaimeiniesta !

I think I would still like a sorted array. Eventually I want to let my users pick from the top 3 or so.

Looks like this is already achieved within `largest` and could be extracted as its own method pretty easily?

**Comment by jjb** [comment]
I have it on my todo list to fix a related problem in about a week from now, so I can potentially work on this feature then.

**Comment by jaimeiniesta** [comment]
That'd be great @jjb!

I also think it should be pretty straightforward to extract the collection of images with their size information to a separate method.

If apart from ordering them all, we could make the `width` and `height` of each image available, it would be great too.

**Comment by jaimeiniesta** [comment]
Closing this, already implemented.
